baseURL = "https://blog.ianmkim.com"
languageCode = "en-US"
title = "Stumbling Blog"
theme="archie"
copyright = "© Ian Kim 2022"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A collection of mistakes, lessons, and poorly conceived ideas. A documentation of my stumblings through Computer Science and Philosophy."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ianmkim"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ianmkim"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
